export { default as ArrowDown } from './ArrowDown'
export { default as ArrowUp } from './ArrowUp'
export { default as Belt } from './Belt'
export { default as PowerRack } from './PowerRack'
export { default as WeightPlate } from './WeightPlate'